// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification payload emitted to the frontend.
 */
export type AutomationNotification = { id: string, task_id: string, task_name: string, notification_type: NotificationType, title: string, body: string, timestamp: string, };

/**
 * An automation run record (maps to `automation_runs` table).
 */
export type AutomationRun = { id: string, task_id: string, status: string, result_text: string | null, error_message: string | null, started_at: string, completed_at: string | null, credits_used: number, };

/**
 * An automation task definition (maps to `automation_tasks` table).
 */
export type AutomationTask = { id: string, name: string, description: string, task_type: string, is_enabled: boolean, is_system: boolean, 
/**
 * The prompt template sent to the agentic runtime. May contain
 * `{{parameter_name}}` placeholders filled in at execution time.
 */
prompt_template: string, 
/**
 * Optional model override (references `models.id`).
 */
model_id: bigint | null, 
/**
 * JSON array of skill names disabled for this automation.
 */
disabled_skills: Array<string>, notify_on_complete: boolean, notify_on_error: boolean, max_iterations: bigint, timeout_seconds: bigint, schedule_type: string | null, schedule_value: string | null, schedule_timezone: string, trigger_type: string | null, trigger_config: string | null, last_run_at: string | null, next_run_at: string | null, created_at: string, updated_at: string, };

/**
 * A semantic trigger definition (maps to `automation_triggers` table).
 */
export type AutomationTrigger = { id: string, task_id: string, trigger_type: string, trigger_config: string, is_enabled: boolean, created_at: string, };

/**
 * Parameters for creating a new automation task.
 */
export type CreateAutomationParams = { name: string, description: string | null, task_type: string, prompt_template: string, model_id: bigint | null, disabled_skills: Array<string> | null, notify_on_complete: boolean | null, notify_on_error: boolean | null, max_iterations: number, timeout_seconds: number, schedule_type: string | null, schedule_value: string | null, schedule_timezone: string | null, trigger_type: string | null, trigger_config: string | null, };

/**
 * Notification type for automation results.
 */
export type NotificationType = "success" | "error" | "warning" | "info";

/**
 * Status of an automation run.
 */
export type RunStatus = "running" | "completed" | "failed" | "cancelled";

/**
 * Schedule type for time-based automations.
 */
export type ScheduleType = "interval" | "daily" | "weekly" | "once";

/**
 * Type of automation task.
 */
export type TaskType = "scheduled" | "semantic";

/**
 * Trigger type for event-based automations.
 */
export type TriggerType = "screen_content" | "app_focus" | "url_visit";

/**
 * Parameters for updating an existing automation task.
 */
export type UpdateAutomationParams = { id: string, name: string | null, description: string | null, prompt_template: string | null, model_id: bigint | null, disabled_skills: Array<string> | null, notify_on_complete: boolean | null, notify_on_error: boolean | null, max_iterations: bigint | null, timeout_seconds: bigint | null, schedule_type: string | null, schedule_value: string | null, schedule_timezone: string | null, trigger_type: string | null, trigger_config: string | null, is_enabled: boolean | null, };
