// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation structure
 */
export type Conversation = { id: string, name: string, created_at: string, updated_at: string, message_count: number, };

/**
 * Message structure
 */
export type Message = { id: string, conversation_id: string, role: Role, content: string, timestamp: string, };

export type Role = "system" | "user" | "assistant";
