// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryEntry } from "./memory";

/**
 * Attachment structure
 */
export type Attachment = { id: string, message_id: string, file_type: string, file_name: string, file_path: string | null, extracted_text: string | null, created_at: string, };

/**
 * Attachment item for list display with conversation context.
 */
export type AttachmentListItem = { id: string, message_id: string, conversation_id: string, conversation_name: string, file_type: string, file_name: string, file_path: string | null, extracted_text: string | null, created_at: string, };

/**
 * Conversation structure
 */
export type Conversation = { id: string, name: string, conv_type: string, created_at: string, updated_at: string, message_count: number, };

/**
 * Message structure
 */
export type Message = { id: string, conversation_id: string, role: Role, content: string, timestamp: string, message_type: MessageType, metadata: MessageMetadata | null, attachments: Array<Attachment>, memory: MemoryEntry | null, };

/**
 * Structured metadata for messages.
 *
 * Different message types carry different metadata
 * that helps with displaying and tracking.
 */
export type MessageMetadata = { "type": "ToolCall", call_id: string, skill_name: string, tool_name: string, arguments: any, thought_signature: string | null, } | { "type": "ToolResult", call_id: string, success: boolean, error: string | null, result: any, } | { "type": "Thinking", stage: string, };

/**
 * The type of a message in the conversation.
 *
 * Different message types represent different stages of agentic
 * processing and are displayed differently in the UI.
 */
export type MessageType = "text" | "tool_call" | "tool_result" | "thinking";

export type Role = "system" | "user" | "assistant" | "tool";
