// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationTextData = { process_id: number, process_name: string | null, application_name: string | null, text_content: Array<string>, };

export type CaptureScreenEvent = { timestamp: string, };

export type ChatStreamEvent = { delta: string, is_finished: boolean, full_response: string, conv_id: string | null, };

export type DetectTasksEvent = { text: string, active_url: string | null, timestamp: string, };

export type ExecuteFunctionEvent = { function_name: string, args: Array<FunctionArgument>, timestamp: string, };

export type FunctionArgument = { key: string, value: string, };

export type GetScreenDiffEvent = { data: Array<ApplicationTextData>, active_url: string | null, timestamp: string, };

export type GetUserAckEvent = { message: string, timestamp: string, };

export type GetUserInputEvent = { message: string, timestamp: string, };

export type HudChatEvent = { text: string, ocr_responses: Array<OcrResponseEvent>, timestamp: string, conv_id: string | null, };

export type OcrResponseEvent = { text: string, success: boolean, timestamp: string, };

export type SummarizeScreenEvent = { text: string, data: Array<ApplicationTextData>, active_url: string | null, timestamp: string, };

export type UpdateTasksEvent = { timestamp: string, };

export type UserAckEvent = { acknowledged: boolean, timestamp: string, };

export type UserInputEvent = { message: string, timestamp: string, };
