// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment, Message } from "./conversations";
import type { MemoryEntry } from "./memory";

export type ApplicationTextData = {
  process_id: number;
  process_name: string | null;
  application_name: string | null;
  text_content: Array<string>;
};

export type AttachmentData = { name: string; file_type: string; data: string };

export type AttachmentsCreatedEvent = {
  message_id: string;
  attachments: Array<Attachment>;
  timestamp: string;
};

export type CaptureScreenEvent = { timestamp: string };

export type ChatStreamEvent = {
  delta: string;
  is_finished: boolean;
  full_response: string;
  conv_id: string | null;
};

export type ComputerUseToastEvent = { message: string; timestamp: string };

export type ComputerUseUpdateEvent = { status: string; message: Message };

export type DetectTasksEvent = {
  text: string;
  active_url: string | null;
  timestamp: string;
};

export type ExtractInteractiveMemoryEvent = {
  message: string;
  message_id: string;
  timestamp: string;
};

export type GenerateConversationNameEvent = {
  conv_id: string;
  message: string;
  timestamp: string;
};

export type GetScreenDiffEvent = {
  data: Array<ApplicationTextData>;
  active_url: string | null;
  timestamp: string;
};

export type HudChatEvent = {
  text: string;
  timestamp: string;
  conv_id: string;
  message_id: string;
  attachments: Array<AttachmentData>;
};

export type MemoryExtractedEvent = { memory: MemoryEntry; timestamp: string };

export type OcrResponseEvent = {
  text: string;
  success: boolean;
  timestamp: string;
};

export type RenameConversationEvent = {
  conv_id: string;
  new_name: string;
  timestamp: string;
};

export type SafetyConfirmationEvent = { reason: string; timestamp: string };

export type SafetyConfirmationResponseEvent = {
  user_confirmed: boolean;
  timestamp: string;
};

export type SummarizeScreenEvent = {
  text: string;
  data: Array<ApplicationTextData>;
  active_url: string | null;
  timestamp: string;
};

export type UpdateTasksEvent = { timestamp: string };
