// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./conversations";
import type { MemoryEntry } from "./memory";

export type AttachmentData = { name: string, file_type: string, data: string, };

export type AttachmentsCreatedEvent = { message_id: string, attachments: Array<Attachment>, timestamp: string, };

export type ChatStreamEvent = { delta: string, is_finished: boolean, full_response: string, conv_id: string | null, message_id: string | null, };

export type CloudUsageDecrementedEvent = { 
/**
 * The model key whose usage was consumed (e.g. "gemini-3-flash").
 */
model_key: string, timestamp: string, };

export type DatabaseRecoveredEvent = { 
/**
 * Path to the backup file containing the user's previous data.
 */
backup_path: string, 
/**
 * Description of the migration error that triggered recovery.
 */
reason: string, timestamp: string, };

export type DownloadFinishedEvent = { id: bigint, };

export type DownloadInformationEvent = { n_items: bigint, content_length: bigint, };

export type DownloadProgressEvent = { id: bigint, total_progress: bigint, };

export type DownloadStartedEvent = { id: bigint, };

export type ExtractInteractiveMemoryEvent = { message: string, message_id: string, timestamp: string, };

export type GenerateConversationNameEvent = { conv_id: string, message: string, timestamp: string, };

export type HudChatEvent = { text: string, timestamp: string, conv_id: string, message_id: string, attachments: Array<AttachmentData>, };

export type MemoryExtractedEvent = { memory: MemoryEntry, timestamp: string, };

export type ModelsChangedEvent = { timestamp: string, };

export type NavigateToConversationEvent = { conversation_id: string, message_id: string | null, timestamp: string, };

export type OcrResponseEvent = { text: string, success: boolean, timestamp: string, };

export type RenameConversationEvent = { conv_id: string, new_name: string, timestamp: string, };

export type TokenUsageChangedEvent = { timestamp: string, };

export type ToolExecutionCompletedEvent = { tool_call_id: string, message_id: string, skill_name: string, tool_name: string, success: boolean, result: any, error: string | null, timestamp: string, };

export type ToolExecutionStartedEvent = { tool_call_id: string, message_id: string, skill_name: string, tool_name: string, content: string, arguments: any, timestamp: string, };
