// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmRequest = { prompt: string, system_prompt: string | null, json_schema: string | null, conv_id: string | null, use_thinking: boolean | null, stream: boolean | null, current_message_id: string | null, tools: any, context_limit: number | null, };
