// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./conversations";
import type { ToolCall, ToolDefinition } from "./skills";

export type LlmRequest = { prompt: string, system_prompt: string | null, json_schema: string | null, conv_id: string | null, use_thinking: boolean | null, stream: boolean | null, current_message_id: string | null, tools: any, internal_tools: Array<ToolDefinition> | null, messages: Array<Message> | null, context_limit: number | null, };

/**
 * Response variants from generation
 */
export type LlmResponse = { "Text": string } | { "ToolCalls": Array<ToolCall> };
