// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GPU device detected by the llama.cpp server.
 */
export type GpuDevice = { 
/**
 * Device name as reported by llama.cpp (e.g. "Vulkan0: NVIDIA GeForce RTX 3080")
 */
name: string, };
