// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryEntry = { id: string, message_id: string, memory_type: string, text: string, embedding: Array<number>, timestamp: string, similarity: number | null, };
