// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for adding a custom (BYOK) model.
 */
export type AddCustomModelParams = { 
/**
 * The model identifier for API requests (e.g. "gpt-4o").
 */
model_id: string, 
/**
 * Full API endpoint URL.
 */
api_url: string, 
/**
 * API authentication key. Empty string treated as None (for localhost models).
 */
api_key: string, 
/**
 * Request format: "openai", "gemini", or "anthropic".
 */
request_format: string, 
/**
 * Provider for display icon (e.g. "openai", "google", "deepseek", "unknown").
 */
provider: string, 
/**
 * Optional display name (max 40 chars). Falls back to model_id.
 */
display_name: string, };

/**
 * Usage info for a single cloud model.
 */
export type CloudModelUsage = { 
/**
 * Daily request limit. -1 means unlimited.
 */
daily_limit: number, requests_used: number, 
/**
 * Remaining uses today. -1 means unlimited.
 */
remaining: number, 
/**
 * Whether this model is accessible on the user's current tier.
 */
is_available: boolean, };

/**
 * Full model access response from the backend.
 * Includes the user's effective tier and per-model usage data.
 */
export type ModelAccessResponse = { 
/**
 * The user's effective tier: "free", "premium", or "admin".
 */
user_tier: string, 
/**
 * Per-model usage keyed by model key (e.g. "gemini-3-flash").
 */
models: { [key in string]?: CloudModelUsage }, };

/**
 * A model entry from the database.
 */
export type ModelEntry = { id: bigint, 
/**
 * Unique model key (e.g. "qwen3vl-2b", "gemini-3-flash", or user-provided).
 */
model: string, 
/**
 * User-friendly name shown in the UI (e.g. "Local", "Gemini 3 Flash").
 */
display_name: string, 
/**
 * Short one-liner for compact contexts like the HUD dropdown.
 */
short_description: string, 
/**
 * Longer description for the full settings page model selector.
 */
description: string, 
/**
 * The model provider for display (e.g. "local", "google", "openai", "deepseek").
 * Resolves to a provider image in the UI: `providers/{provider}.png`.
 */
provider: string, is_cloud: boolean, is_premium: boolean, daily_limit: number | null, 
/**
 * Whether this model is enabled/visible in the UI.
 */
is_enabled: boolean, 
/**
 * Whether this is an internal (built-in) model vs. user-added BYOK model.
 */
is_internal: boolean, 
/**
 * API endpoint URL for BYOK models (e.g. "https://api.openai.com/v1/chat/completions").
 */
api_url: string | null, 
/**
 * API key for BYOK models. Stored encrypted in SQLCipher DB. Optional for localhost models.
 */
api_key: string | null, 
/**
 * Request format: "openai", "gemini", or "anthropic". Determines which provider to route to.
 */
request_format: string, 
/**
 * The model identifier sent in API requests (e.g. "gpt-4o", "claude-3-5-sonnet-20241022").
 * For internal models this is NULL since they use their own routing.
 */
model_id: string | null, };

/**
 * Parameters for updating a custom (BYOK) model.
 */
export type UpdateCustomModelParams = { 
/**
 * The current model key (used to find the row).
 */
model_key: string, 
/**
 * Updated model identifier for API requests.
 */
model_id: string, 
/**
 * Updated API endpoint URL.
 */
api_url: string, 
/**
 * Updated API key. Empty string treated as None.
 */
api_key: string, 
/**
 * Updated request format.
 */
request_format: string, 
/**
 * Updated provider for display icon.
 */
provider: string, 
/**
 * Updated display name (max 40 chars).
 */
display_name: string, };
