// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for adding a custom (BYOK) model.
 */
export type AddCustomModelParams = { 
/**
 * The model identifier for API requests (e.g. "gpt-4o").
 */
model: string, 
/**
 * Full API endpoint URL.
 */
api_url: string, 
/**
 * API authentication key. Empty string treated as None (for localhost models).
 */
api_key: string, 
/**
 * Request format: "openai", "gemini", or "anthropic".
 */
request_format: string, 
/**
 * Provider for display icon (e.g. "openai", "google", "deepseek", "unknown").
 */
provider: string, 
/**
 * Optional display name (max 40 chars). Falls back to model.
 */
display_name: string, };

/**
 * Global credit usage info for the authenticated user.
 */
export type CreditUsageInfo = { 
/**
 * Daily credit limit. -1 means unlimited.
 */
daily_credit_limit: number, 
/**
 * Credits consumed today.
 */
credits_used: number, 
/**
 * Credits remaining today. -1 means unlimited.
 */
credits_remaining: number, 
/**
 * Per-model credit costs keyed by model key (e.g. "gemini-3-flash" → 1.0).
 */
model_costs: { [key in string]?: number }, };

/**
 * Full credit usage response from the backend.
 */
export type CreditUsageResponse = { 
/**
 * The user's effective tier: "free", "premium", or "admin".
 */
user_tier: string, 
/**
 * Global credit usage data.
 */
daily_credit_limit: number, credits_used: number, credits_remaining: number, 
/**
 * Per-model credit costs keyed by model key (e.g. "gemini-3-flash" → 1.0).
 */
model_costs: { [key in string]?: number }, };

/**
 * A model entry from the database.
 */
export type ModelEntry = { id: number, 
/**
 * Model identifier sent in API requests (e.g. "qwen3vl-2b", "gpt-4o").
 * NOT unique — use `id` for lookups.
 */
model: string, 
/**
 * User-friendly name shown in the UI (e.g. "Local", "Gemini 3 Flash").
 */
display_name: string, 
/**
 * Short one-liner for compact contexts like the HUD dropdown.
 */
short_description: string, 
/**
 * Longer description for the full settings page model selector.
 */
description: string, 
/**
 * The model provider for display (e.g. "local", "google", "openai", "deepseek").
 * Resolves to a provider image in the UI: `providers/{provider}.png`.
 */
provider: string, is_cloud: boolean, 
/**
 * Whether this model is enabled/visible in the UI.
 */
is_enabled: boolean, 
/**
 * Whether this is an internal (built-in) model vs. user-added BYOK model.
 */
is_internal: boolean, 
/**
 * API endpoint URL for BYOK models (e.g. "https://api.openai.com/v1/chat/completions").
 */
api_url: string | null, 
/**
 * API key for BYOK models. Stored encrypted in SQLCipher DB. Optional for localhost models.
 */
api_key: string | null, 
/**
 * Request format: "openai", "gemini", or "anthropic". Determines which provider to route to.
 */
request_format: string, };

/**
 * Parameters for updating a custom (BYOK) model.
 */
export type UpdateCustomModelParams = { 
/**
 * The database id of the model to update.
 */
id: bigint, 
/**
 * Updated model identifier for API requests.
 */
model: string, 
/**
 * Updated API endpoint URL.
 */
api_url: string, 
/**
 * Updated API key. Empty string treated as None.
 */
api_key: string, 
/**
 * Updated request format.
 */
request_format: string, 
/**
 * Updated provider for display icon.
 */
provider: string, 
/**
 * Updated display name (max 40 chars).
 */
display_name: string, };
