// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HudDimensions = {
  chat_width: number;
  input_bar_height: number;
  chat_max_height: number;
  login_width: number;
  login_height: number;
};

/**
 * HUD size options for the user interface
 */
export type HudSizeOption = "Small" | "Normal" | "Large";

export type HudState = "Input" | "Chat" | "Login" | "Default";

export type ModelSelection = "Local" | "Fast" | "Pro";

export type UserSettings = {
  hud_size: HudSizeOption;
  model_selection: ModelSelection;
};
