// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HudDimensions = { width: number, collapsed_height: number, expanded_height: number, };

export type HudSizeOption = "Small" | "Normal" | "Large";

export type UserSettings = { hud_size: HudSizeOption, };
