// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for the agentic runtime.
 *
 * These settings control the behavior of the agent loop,
 * including context limits and execution boundaries.
 */
export type AgentRuntimeConfig = { 
/**
 * Maximum number of conversation history messages to include for local models.
 *
 * Local models typically have smaller context windows, so we limit
 * history more aggressively.
 */
local_context_limit: number, 
/**
 * Maximum number of conversation history messages to include for cloud models.
 *
 * Cloud models typically have larger context windows.
 */
cloud_context_limit: number, 
/**
 * Maximum number of tool calls that can be made in a single turn.
 *
 * This prevents infinite loops and excessive tool usage.
 */
max_tool_calls_per_turn: number, 
/**
 * Maximum total iterations in the agentic loop before giving up.
 *
 * Each iteration represents a round of (model request -> response -> tool execution).
 */
max_iterations: number, 
/**
 * Whether to emit thinking/reasoning messages to the frontend.
 *
 * When enabled, the model's internal reasoning is shown as
 * separate "thinking" messages in the conversation.
 */
enable_thinking: boolean, };

export type HudDimensions = { chat_width: number, input_bar_height: number, chat_max_height: number, login_width: number, login_height: number, };

/**
 * HUD size options for user interface
 */
export type HudSizeOption = "Small" | "Normal" | "Large";

export type HudState = "Input" | "Chat" | "Login" | "Default";

export type ModelSelection = "Local" | "Fast" | "Pro";

export type UserSettings = { hud_size: HudSizeOption, model_selection: ModelSelection, agent_config: AgentRuntimeConfig, };
