// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The data type of a tool parameter.
 */
export type ParameterType = "string" | "integer" | "number" | "boolean" | "array" | "object";

/**
 * Skill summary for progressive disclosure (Phase 1).
 *
 * Only the name and description are sent to the model initially,
 * minimizing context overhead. Full tool definitions are loaded
 * just-in-time when a skill is activated.
 */
export type SkillSummary = { 
/**
 * The unique identifier for this skill (e.g., "web-search", "memory-search")
 */
name: string, 
/**
 * A brief description of what this skill does.
 * This is shown to the LLM to help it decide when to activate the skill.
 */
description: string, };

/**
 * A tool call requested by the model.
 *
 * This represents a single invocation request that the agent runtime
 * needs to execute and return results for.
 */
export type ToolCall = { 
/**
 * A unique identifier for this tool call, used to match results.
 */
id: string, 
/**
 * The name of the skill this tool belongs to.
 */
skill_name: string, 
/**
 * The specific tool to invoke within the skill.
 */
tool_name: string, 
/**
 * The arguments to pass to the tool, as JSON.
 */
arguments: any, };

/**
 * Tool definition in the unified internal format.
 *
 * This is our canonical representation of a tool, which gets
 * translated to provider-specific formats (OpenAI, Gemini) at runtime.
 */
export type ToolDefinition = { 
/**
 * The unique name of this tool (within its skill).
 */
name: string, 
/**
 * A description of what this tool does, helping the LLM decide when to use it.
 */
description: string, 
/**
 * The parameters this tool accepts.
 */
parameters: Array<ToolParameter>, 
/**
 * Optional schema describing the return type of this tool.
 */
returns: ToolReturnType | null, };

/**
 * A parameter definition for a tool.
 */
export type ToolParameter = { 
/**
 * The parameter name.
 */
name: string, 
/**
 * The type of this parameter.
 */
type: ParameterType, 
/**
 * A description of this parameter.
 */
description: string, 
/**
 * Whether this parameter is required.
 */
required: boolean, 
/**
 * An optional default value for this parameter.
 */
default: any, };

/**
 * Result from executing a tool.
 *
 * This contains the outcome of a tool execution, either
 * a successful result or an error message.
 */
export type ToolResult = { 
/**
 * The ID of the tool call this result corresponds to.
 */
call_id: string, 
/**
 * Whether the tool execution succeeded.
 */
success: boolean, 
/**
 * The successful result value (as JSON), if successful.
 */
result: any, 
/**
 * An error message, if the execution failed.
 */
error: string | null, };

/**
 * Schema describing the return type of a tool.
 */
export type ToolReturnType = { 
/**
 * The type identifier (e.g., "array", "object", "string").
 */
type: string, 
/**
 * For object types, the properties of the object.
 */
properties: any, 
/**
 * For array types, the schema of the array items.
 */
items: ToolReturnType | null, };
