// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompletedStepDetection = { step_id: bigint, confidence: number, evidence: string, reasoning: string, };

export type CreateTaskRequest = { name: string, description: string, category: string | null, priority: number, frequency: TaskFrequency, steps: Array<CreateTaskStepRequest>, };

export type CreateTaskStepRequest = { title: string, description: string, };

export type InProgressStepDetection = { step_id: bigint, confidence: number, evidence: string, };

export type ScreenContext = { text: string, application: string, window_title: string | null, timestamp: string, };

export type StepStatus = "Pending" | "InProgress" | "Completed" | "Skipped";

export type StepUpdate = { step_id: bigint, status: StepStatus, confidence: number, evidence: string, reasoning: string | null, };

export type Task = { id: bigint, name: string, description: string, category: string | null, priority: number, frequency: string, last_completed_at: string | null, next_due_at: string | null, created_at: string, updated_at: string, status: string, };

export type TaskDetectionResult = { completed_steps: Array<CompletedStepDetection>, in_progress_steps: Array<InProgressStepDetection>, };

export type TaskFrequency = "OneTime" | "Daily" | "Weekly" | "BiWeekly" | "Monthly" | "Quarterly" | "Yearly" | { "Custom": number };

export type TaskProgress = { id: bigint, task_id: bigint, step_id: bigint | null, llm_confidence: number, evidence: string | null, reasoning: string | null, timestamp: string, };

export type TaskProgressUpdate = { task_id: bigint, step_updates: Array<StepUpdate>, overall_status: TaskStatus, };

export type TaskStatus = "Pending" | "InProgress" | "Completed" | "Paused";

export type TaskStep = { id: bigint, task_id: bigint, step_number: number, title: string, description: string, status: string, completed_at: string | null, };

export type TaskWithSteps = { task: Task, steps: Array<TaskStep>, progress_percentage: number, };
