// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompletedStepDetection = { step_id: bigint, reasoning: string, };

export type CreateTaskRequest = { name: string, description: string, category: string | null, priority: number, frequency: TaskFrequency, steps: Array<CreateTaskStepRequest>, };

export type CreateTaskStepRequest = { title: string, description: string, };

export type ScreenContext = { text: string, application: string, window_title: string | null, timestamp: string, };

export type StepStatus = "Pending" | "Completed";

export type StepUpdate = { step_id: bigint, status: StepStatus, reasoning: string | null, };

export type Task = { id: bigint, name: string, description: string, category: string | null, priority: number, frequency: string, last_completed_at: string | null, first_scheduled_at: string, created_at: string, updated_at: string, status: string, };

export type TaskDetectionResult = { completed_steps: Array<CompletedStepDetection>, };

export type TaskFrequency = "OneTime" | "Daily" | "Weekly" | "BiWeekly" | "Monthly" | "Quarterly" | "Yearly" | { "Custom": number };

export type TaskProgress = { id: bigint, task_id: bigint, step_id: bigint | null, reasoning: string | null, timestamp: string, };

export type TaskProgressUpdate = { task_id: bigint, step_updates: Array<StepUpdate>, overall_status: TaskStatus, };

export type TaskStatus = "Pending" | "Completed";

export type TaskStatusCounts = { total: number, pending: number, completed: number, overdue: number, due_today: number, };

export type TaskStep = { id: bigint, task_id: bigint, step_number: number, title: string, description: string, status: string, completed_at: string | null, };

export type TaskWithSteps = { task: Task, steps: Array<TaskStep>, progress_percentage: number, };

export type UpdateTaskRequest = { id: bigint, name: string, description: string, category: string | null, priority: number, frequency: TaskFrequency, steps: Array<CreateTaskStepRequest>, };
