// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregationLevel = "Hour" | "Day" | "Week" | "Month";

/**
 * Time filters for querying token usage
 */
export type TimeFilter = "Last7Days" | "Last30Days" | "Last3Months";

export type TokenUsageConsumptionResult = { cost_amount: number, cost_unit: string, water_amount: number, water_unit: string, energy_amount: number, energy_unit: string, };

export type TokenUsageQueryResult = { time_filter: TimeFilter, aggregation_level: AggregationLevel, data: ({ time_label: string, date: string } & Record<string, number>)[], models: Array<string>, total_prompt_tokens: bigint, total_completion_tokens: bigint, time_range: string, };
