// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregationLevel = "Hour" | "Day" | "Week" | "Month";

/**
 * Time filters for querying token usage
 */
export type TimeFilter = "Last24Hours" | "Last7Days" | "Last30Days" | "LastYear" | "AllTime";

export type TokenUsageQueryResult = { time_filter: TimeFilter, aggregation_level: AggregationLevel, data: ({ time_label: string, date: string } & Record<string, number>)[], models: Array<string>, total_prompt_tokens: number, total_completion_tokens: number, time_range: string, };
